name: Aurelia-Guides Blogs
description:     Guide to build Aurelia Applications
paginate: 10
markdown: rdiscount
permalink: pretty
highlighter: pygments

logo:             logo.png
disqus_shortname: # register a disqus account if you want to enable comments

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
